/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes/index'
import { Route as QuotesWizardRouteImport } from './routes/quotes/wizard'
import { Route as QuotesSuccessRouteImport } from './routes/quotes/success'
import { Route as QuotesRequestRouteImport } from './routes/quotes/request'
import { Route as QuotesCreateRouteImport } from './routes/quotes/create'
import { Route as QuotesQuoteIdIndexRouteImport } from './routes/quotes/$quoteId/index'
import { Route as QuotesQuoteIdEditRouteImport } from './routes/quotes/$quoteId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesWizardRoute = QuotesWizardRouteImport.update({
  id: '/quotes/wizard',
  path: '/quotes/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesSuccessRoute = QuotesSuccessRouteImport.update({
  id: '/quotes/success',
  path: '/quotes/success',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRequestRoute = QuotesRequestRouteImport.update({
  id: '/quotes/request',
  path: '/quotes/request',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesCreateRoute = QuotesCreateRouteImport.update({
  id: '/quotes/create',
  path: '/quotes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdIndexRoute = QuotesQuoteIdIndexRouteImport.update({
  id: '/quotes/$quoteId/',
  path: '/quotes/$quoteId/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdEditRoute = QuotesQuoteIdEditRouteImport.update({
  id: '/quotes/$quoteId/edit',
  path: '/quotes/$quoteId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quotes/create': typeof QuotesCreateRoute
  '/quotes/request': typeof QuotesRequestRoute
  '/quotes/success': typeof QuotesSuccessRoute
  '/quotes/wizard': typeof QuotesWizardRoute
  '/quotes/': typeof QuotesIndexRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quotes/create': typeof QuotesCreateRoute
  '/quotes/request': typeof QuotesRequestRoute
  '/quotes/success': typeof QuotesSuccessRoute
  '/quotes/wizard': typeof QuotesWizardRoute
  '/quotes': typeof QuotesIndexRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quotes/create': typeof QuotesCreateRoute
  '/quotes/request': typeof QuotesRequestRoute
  '/quotes/success': typeof QuotesSuccessRoute
  '/quotes/wizard': typeof QuotesWizardRoute
  '/quotes/': typeof QuotesIndexRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quotes/create'
    | '/quotes/request'
    | '/quotes/success'
    | '/quotes/wizard'
    | '/quotes/'
    | '/quotes/$quoteId/edit'
    | '/quotes/$quoteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quotes/create'
    | '/quotes/request'
    | '/quotes/success'
    | '/quotes/wizard'
    | '/quotes'
    | '/quotes/$quoteId/edit'
    | '/quotes/$quoteId'
  id:
    | '__root__'
    | '/'
    | '/quotes/create'
    | '/quotes/request'
    | '/quotes/success'
    | '/quotes/wizard'
    | '/quotes/'
    | '/quotes/$quoteId/edit'
    | '/quotes/$quoteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuotesCreateRoute: typeof QuotesCreateRoute
  QuotesRequestRoute: typeof QuotesRequestRoute
  QuotesSuccessRoute: typeof QuotesSuccessRoute
  QuotesWizardRoute: typeof QuotesWizardRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  QuotesQuoteIdEditRoute: typeof QuotesQuoteIdEditRoute
  QuotesQuoteIdIndexRoute: typeof QuotesQuoteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/wizard': {
      id: '/quotes/wizard'
      path: '/quotes/wizard'
      fullPath: '/quotes/wizard'
      preLoaderRoute: typeof QuotesWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/success': {
      id: '/quotes/success'
      path: '/quotes/success'
      fullPath: '/quotes/success'
      preLoaderRoute: typeof QuotesSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/request': {
      id: '/quotes/request'
      path: '/quotes/request'
      fullPath: '/quotes/request'
      preLoaderRoute: typeof QuotesRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/create': {
      id: '/quotes/create'
      path: '/quotes/create'
      fullPath: '/quotes/create'
      preLoaderRoute: typeof QuotesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId/': {
      id: '/quotes/$quoteId/'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId/'
      preLoaderRoute: typeof QuotesQuoteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId/edit': {
      id: '/quotes/$quoteId/edit'
      path: '/quotes/$quoteId/edit'
      fullPath: '/quotes/$quoteId/edit'
      preLoaderRoute: typeof QuotesQuoteIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuotesCreateRoute: QuotesCreateRoute,
  QuotesRequestRoute: QuotesRequestRoute,
  QuotesSuccessRoute: QuotesSuccessRoute,
  QuotesWizardRoute: QuotesWizardRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  QuotesQuoteIdEditRoute: QuotesQuoteIdEditRoute,
  QuotesQuoteIdIndexRoute: QuotesQuoteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
